### ISSUE TITLE
add-global-table throws java.lang.UnsupportedOperationException - clojure.lang.APersistentMap/clear

### ISSUE THREAD

**Issue by smessems** [dvlopt/kafka.clj#5]
Hi, first I wanted to say that this is a beautiful piece for software. It seems that lots of thinking was made to provide the right abstractions and idiomatic usage.
I am transforming my project to the new version of the library.
I encountered an exception when adding global table. looks like there is a call to  'clear' method on a persistent structure. 

```
       APersistentMap.java:  298  clojure.lang.APersistentMap/clear
         Materialized.java:  203  org.apache.kafka.streams.kstream.Materialized/withLoggingDisabled
InternalStreamsBuilder.java:  120  org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder/globalTable
       StreamsBuilder.java:  403  org.apache.kafka.streams.StreamsBuilder/globalTable
               builder.clj:  229  dvlopt.kstreams.builder/add-global-table
               builder.clj:  209  dvlopt.kstreams.builder/add-global-table
```

Have you encounter that?

**Comment by dvlopt** [comment]
Hi,

Thanks ! Yes, it took me a while to find the right abstractions. Kafka is such a good fit for Clojure, it deserves a good lib. And I want it to have a good documentation because it is not easy to navigate efficiently in the javadocs and have a clear picture of what is happening. Feel free to provide some feedback.

For some reason, Kafka Streams is indeed trying to clear the configuration map. Even in the absence of this map, an empty persistent one was being passed in order to avoid NullPointerExceptions. Check version 1.0.0-beta2 ;)
